CREATE TABLE downote.notes (
  id INT(40) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  note_header VARCHAR(255),
  note_text TEXT,
  note_order INT(8) UNSIGNED NOT NULL,
  user_id INT(8) UNSIGNED NOT NULL,
  FOREIGN KEY (user_id) REFERENCES downote.users(id) ON DELETE CASCADE
);
